#
# [ Database Configuration Section ]
#
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.167:5432/dev
    username: firefox7025
    password: JessiBear1995*
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
