#
# [ Database Configuration Section ]
#
spring:
  datasource:
    url: jdbc:postgresql://104.196.248.247:5432/registry
    username: firefox7025
    password: JessiBear1995*
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: 8080
